site_name: Meine Bookmarks
theme:
  name: readthedocs
plugins:
  - search
  - gen-nav:
      root: docs
      index: index.md
      strip_number_prefix: true
      exclude:
        - "*/_archive/*"
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
